# remove pc container
docker rm -f pc
# remove pdb container
docker rm -f pdb
# remove DAN container
docker rm -f dan
# remove LDB containers
docker rm -f ldb.search
docker rm -f ldb
# remove Mongo container
docker rm -f operando.mongo
# remove MySQL container
docker rm -f operando.mysql
# remove AAPI containers
docker rm -f aapi
docker rm -f cas
docker rm -f openldap
# remove DNS container
docker rm -f dnsmasq
