#*******************************************************************************
#*  # Copyright (c) 2016 {UPRC}.
#*  # All rights reserved. This program and the accompanying materials
#*  # are made available under the terms of the The MIT License (MIT).
#*  # which accompanies this distribution, and is available at
#*  # http://opensource.org/licenses/MIT
#*
#*  # Contributors:
#*  #    {Constantinos Patsakis} {UPRC}
#*  #    {Stamatis Glykos} {UPRC}
#*  #    {Constantinos Alexandris} {UPRC}
#*  # Initially developed in the context of OPERANDO EU project www.operando.eu
#*******************************************************************************/

repositoryManagers:
- name: Ami
  serviceId: op-pdr/rpm/built-in
  schema: http
  host: 192.168.101.166
  port: 80
  serviceRoot: /AmiOData/AmiOdataService.svc
